### ISSUE TITLE
Get example data

### ISSUE THREAD

**Issue by rogerkuou** [MotionbyLearing/Planning#12]
There are three example data we need from Freek:

1. KNMI contextual data (#11)
2. Example data for investigating InSAR storage formats (#9 and #10). This  
3. Example data for investigating training strategy. Ideally, this can be the data used in the RNN paper.

**Comment by rogerkuou** [comment]
Freek will give examples on interferometric (raster) and PSI (pointset)

**Comment by FreekvanLeijen** [comment]
Regarding KNMI contextual data, see my post at #11 .

Regarding examples of InSAR data, see Spider:
- Doris Rippl output, see e.g.
/project/caroline/Share/stacks/nl_s1_dsc_t037_old/sentinel1/Benelux_track_37/20181216

Here, you find for a certain date an info.json file with metadata, and phase_corrected_VV@radar.raw with the coregistered, resampled and topographic phase corrected SLC. The stack of these SLC's will be the main input for the time series analysis. The data format is 'complex_short' which means complex data in 'half' precision format (see e.g. https://en.wikipedia.org/wiki/Half-precision_floating-point_format).

- DePSI time series analysis, see e.g.,

/project/caroline/Share/projects/delft_tsx_asc/psi/run2

DePSI provides a lot of intermediate results in a flat binary (single/double) format. This is something I would like to change in the near future to a space-time matrix format. I share an example implementation in Matlab. However, we should choose a file format, see #10 ).

**Comment by rogerkuou** [comment]
Here are two attachments Freek created, regarding the relevant example data: 

- the [LPS22_mobyle.pdf](https://github.com/MotionbyLearing/Planning/files/9190205/LPS22_mobyle.pdf) document, where Freek inserted some notes regarding presentations he saw during the ESA Living Planet symposium last May. There may be some interesting links there.

- [stmutil.zip](https://github.com/MotionbyLearing/Planning/files/9190207/stmutil.zip), the current version of our Matlab space-time matrix implementation for point-time series. Currently stored in .mat files, but something like this can be stored in hdf5/netcdf/zarr/..... To be studied in the sprint.
